version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/app
    ports:
      - "8001:8000"

    environment:
      - DEBUG=True
      - PYTHONUNBUFFERED=1